In [2]:
import pandas as pd
import numpy as np

In [2]:
#实现缺失值处理丢弃
df=pd.read_csv('../data/player_attributes.csv')
df.head(2)
#使用dropna（）实现pLayer_attributes球员评价数据表下的缺失值丢弃
#只要有任何－一个记录有缺失，则删除整行
df.dropna().isnull() .any().sum()
#只要有任何一个记录有缺失，则删除整列
df.dropna(axis=1)
#只考虑vision列和sLiding_tackle列，只要有任何一个记录缺失，则删除该行
df.dropna(subset=['vision','sliding_tackle'])
#使用notnuLl（）方法过滤缺失值数据
# 过滤掉overall_rating为空的行记录
df[df.overall_rating.notnull()]

,id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,0,505942,2016/2/18 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,1,505942,2015/11/19 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0

0

            id  player_api_id             date
0            0         505942   2016/2/18 0:00
1            1         505942  2015/11/19 0:00
2            2         505942   2015/9/21 0:00
3            3         505942   2015/3/20 0:00
4            4         505942   2007/2/22 0:00
...        ...            ...              ...
183973  183973          39902   2009/8/30 0:00
183974  183974          39902   2009/2/22 0:00
183975  183975          39902   2008/8/30 0:00
183976  183976          39902   2007/8/30 0:00
183977  183977          39902   2007/2/22 0:00

[183978 rows x 3 columns]

,id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,0,505942,2016/2/18 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,1,505942,2015/11/19 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,2,505942,2015/9/21 0:00,62.0,66.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,3,505942,2015/3/20 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,4,505942,2007/2/22 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183973,183973,39902,2009/8/30 0:00,83.0,85.0,right,medium,low,84.0,77.0,...,88.0,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0
183974,183974,39902,2009/2/22 0:00,78.0,80.0,right,medium,low,74.0,76.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183975,183975,39902,2008/8/30 0:00,77.0,80.0,right,medium,low,74.0,71.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183976,183976,39902,2007/8/30 0:00,78.0,81.0,right,medium,low,74.0,64.0,...,88.0,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0
183977,183977,39902,2007/2/22 0:00,80.0,81.0,right,medium,low,74.0,68.0,...,88.0,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0

,id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,0,505942,2016/2/18 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,1,505942,2015/11/19 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,2,505942,2015/9/21 0:00,62.0,66.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,3,505942,2015/3/20 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,4,505942,2007/2/22 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183973,183973,39902,2009/8/30 0:00,83.0,85.0,right,medium,low,84.0,77.0,...,88.0,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0
183974,183974,39902,2009/2/22 0:00,78.0,80.0,right,medium,low,74.0,76.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183975,183975,39902,2008/8/30 0:00,77.0,80.0,right,medium,low,74.0,71.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183976,183976,39902,2007/8/30 0:00,78.0,81.0,right,medium,low,74.0,64.0,...,88.0,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0
183977,183977,39902,2007/2/22 0:00,80.0,81.0,right,medium,low,74.0,68.0,...,88.0,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0

In [3]:
#实现缺失值处理填充
df = pd.read_csv('../data/player_attributes.csv')
# 使用fillna（)实现player_attributes表缺失数据的填充
# 为方便查看结果，取overallrating为空的全部记录和部分随机抽取的记录
a=df[df.overall_rating.isna()]
a.sample(10)
# 将缺失的数据统一填充为-1
a.fillna(-1)
# 将overallrating的值设置为该列的均值
df.overall_rating.mean()
a.fillna(df.overall_rating.mean() .round(2))
# 将overall_rating的值设置为该列上一个有效值
df.overall_rating.fillna(method='ffill')
#使用行列混合操作填充指定列
# 将overall_rating为空的数据填充为对应potential列的均值
df.potential.mean()
df.overall_rating=df.overall_rating.fillna(df.potential.mean())
df.query('overall_rating==@df.potential.mean()')

,id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
145721,145721,68766,2007/2/22 0:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138982,138982,193866,2015/10/30 0:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44138,44138,42168,2007/2/22 0:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123917,123917,34031,2007/2/22 0:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178612,178612,37577,2007/2/22 0:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143961,143961,13437,2007/2/22 0:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39995,39995,32323,2007/2/22 0:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112337,112337,27615,2007/2/22 0:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162190,162190,41726,2007/2/22 0:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156272,156272,24168,2007/2/22 0:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

C:\Users\123\AppData\Local\Temp\ipykernel_19880\942144272.py:8: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  a.fillna(-1)

,id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
483,483,31684,2007/2/22 0:00,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
983,983,29904,2007/2/22 0:00,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
1752,1752,24159,2007/2/22 0:00,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2089,2089,31916,2007/2/22 0:00,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2482,2482,37249,2007/2/22 0:00,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182587,182587,25538,2007/2/22 0:00,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
183249,183249,32633,2007/2/22 0:00,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
183309,183309,33823,2007/2/22 0:00,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
183361,183361,25772,2007/2/22 0:00,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
183487,183487,38843,2007/2/22 0:00,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0

68.6000152886831

C:\Users\123\AppData\Local\Temp\ipykernel_19880\942144272.py:11: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  a.fillna(df.overall_rating.mean() .round(2))

,id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
483,483,31684,2007/2/22 0:00,68.6,68.6,68.6,68.6,68.6,68.6,68.6,...,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6
983,983,29904,2007/2/22 0:00,68.6,68.6,68.6,68.6,68.6,68.6,68.6,...,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6
1752,1752,24159,2007/2/22 0:00,68.6,68.6,68.6,68.6,68.6,68.6,68.6,...,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6
2089,2089,31916,2007/2/22 0:00,68.6,68.6,68.6,68.6,68.6,68.6,68.6,...,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6
2482,2482,37249,2007/2/22 0:00,68.6,68.6,68.6,68.6,68.6,68.6,68.6,...,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182587,182587,25538,2007/2/22 0:00,68.6,68.6,68.6,68.6,68.6,68.6,68.6,...,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6
183249,183249,32633,2007/2/22 0:00,68.6,68.6,68.6,68.6,68.6,68.6,68.6,...,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6
183309,183309,33823,2007/2/22 0:00,68.6,68.6,68.6,68.6,68.6,68.6,68.6,...,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6
183361,183361,25772,2007/2/22 0:00,68.6,68.6,68.6,68.6,68.6,68.6,68.6,...,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6
183487,183487,38843,2007/2/22 0:00,68.6,68.6,68.6,68.6,68.6,68.6,68.6,...,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6,68.6

C:\Users\123\AppData\Local\Temp\ipykernel_19880\942144272.py:13: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.overall_rating.fillna(method='ffill')

0         67.0
1         67.0
2         62.0
3         61.0
4         61.0
          ...
183973    83.0
183974    78.0
183975    77.0
183976    78.0
183977    80.0
Name: overall_rating, Length: 183978, dtype: float64

73.46035316857957

,id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
483,483,31684,2007/2/22 0:00,73.460353,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
983,983,29904,2007/2/22 0:00,73.460353,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1752,1752,24159,2007/2/22 0:00,73.460353,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2089,2089,31916,2007/2/22 0:00,73.460353,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2482,2482,37249,2007/2/22 0:00,73.460353,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182587,182587,25538,2007/2/22 0:00,73.460353,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183249,183249,32633,2007/2/22 0:00,73.460353,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183309,183309,33823,2007/2/22 0:00,73.460353,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183361,183361,25772,2007/2/22 0:00,73.460353,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183487,183487,38843,2007/2/22 0:00,73.460353,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#在球员评价数据表中，球员评分（overall_rating）出现了负分数或者超过1θθ的分数，可以对其进行丢弃
df = pd.read_csv('../data/player_attributes.csv')
df
df.query('overall_rating>=0 & overall_rating<=100')
df[(df.overall_rating>=0) & (df.overall_rating<=100)]

,id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,0,505942,2016/2/18 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,1,505942,2015/11/19 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,2,505942,2015/9/21 0:00,62.0,66.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,3,505942,2015/3/20 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,4,505942,2007/2/22 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183973,183973,39902,2009/8/30 0:00,83.0,85.0,right,medium,low,84.0,77.0,...,88.0,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0
183974,183974,39902,2009/2/22 0:00,78.0,80.0,right,medium,low,74.0,76.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183975,183975,39902,2008/8/30 0:00,77.0,80.0,right,medium,low,74.0,71.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183976,183976,39902,2007/8/30 0:00,78.0,81.0,right,medium,low,74.0,64.0,...,88.0,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0
183977,183977,39902,2007/2/22 0:00,80.0,81.0,right,medium,low,74.0,68.0,...,88.0,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0

,id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,0,505942,2016/2/18 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,1,505942,2015/11/19 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,2,505942,2015/9/21 0:00,62.0,66.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,3,505942,2015/3/20 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,4,505942,2007/2/22 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183973,183973,39902,2009/8/30 0:00,83.0,85.0,right,medium,low,84.0,77.0,...,88.0,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0
183974,183974,39902,2009/2/22 0:00,78.0,80.0,right,medium,low,74.0,76.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183975,183975,39902,2008/8/30 0:00,77.0,80.0,right,medium,low,74.0,71.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183976,183976,39902,2007/8/30 0:00,78.0,81.0,right,medium,low,74.0,64.0,...,88.0,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0
183977,183977,39902,2007/2/22 0:00,80.0,81.0,right,medium,low,74.0,68.0,...,88.0,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0

,id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,0,505942,2016/2/18 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,1,505942,2015/11/19 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,2,505942,2015/9/21 0:00,62.0,66.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,3,505942,2015/3/20 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,4,505942,2007/2/22 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183973,183973,39902,2009/8/30 0:00,83.0,85.0,right,medium,low,84.0,77.0,...,88.0,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0
183974,183974,39902,2009/2/22 0:00,78.0,80.0,right,medium,low,74.0,76.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183975,183975,39902,2008/8/30 0:00,77.0,80.0,right,medium,low,74.0,71.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183976,183976,39902,2007/8/30 0:00,78.0,81.0,right,medium,low,74.0,64.0,...,88.0,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0
183977,183977,39902,2007/2/22 0:00,80.0,81.0,right,medium,low,74.0,68.0,...,88.0,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0

In [5]:
#df.dtypes
#足球数据表集中，出现了负分数或者超过100的分数可以对其进行修正
#<0的分数设置为0
#>100的分数设置为100
#使用两种方法实现异常值的恢复
df = pd.read_csv('../data/player_attributes.csv')
df.dtypes
df.loc[df.overall_rating<50,'overall_rating']=-50
df.loc[df.overall_rating>50,'overall_rating']=101
for col in df.columns:
#'object'==df[col].dtype
#过滤掉列名带id的
    if 'id' not in col and'object' != df[col].dtype:
        df.loc[df[col]<0,col].size
        df.loc[df[col]>100,col].size
        df.loc[df[col]<0,col]=0
        df.loc[df[col]>100,col]=100

id                       int64
player_api_id            int64
date                    object
overall_rating         float64
potential              float64
preferred_foot          object
attacking_work_rate     object
defensive_work_rate     object
crossing               float64
finishing              float64
heading_accuracy       float64
short_passing          float64
volleys                float64
dribbling              float64
curve                  float64
free_kick_accuracy     float64
long_passing           float64
ball_control           float64
acceleration           float64
sprint_speed           float64
agility                float64
reactions              float64
balance                float64
shot_power             float64
jumping                float64
stamina                float64
strength               float64
long_shots             float64
aggression             float64
interceptions          float64
positioning            float64
vision                 float64
penalties              float64
marking                float64
standing_tackle        float64
sliding_tackle         float64
gk_diving              float64
gk_handling            float64
gk_kicking             float64
gk_positioning         float64
gk_reflexes            float64
dtype: object

1154

181402

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0