In [2]:
import numpy as np
import pandas as pd

In [19]:
#1球员身高的Series
a=['188cm','180cm','178cm','189cm','191cm','180cm',np.NaN]
s1=pd.Series([i for i in a],index=[i for i in range(1,8)])
s1

1    188cm
2    180cm
3    178cm
4    189cm
5    191cm
6    180cm
7      NaN
dtype: object

In [20]:
#2不为空的球员个数
s1.count()

6

In [21]:
#3身高数据去掉cm
s1=s1.str.replace('[^0-9]+','',regex=True)
s1

1    188
2    180
3    178
4    189
5    191
6    180
7    NaN
dtype: object

In [22]:
#4 180身高的球员个数
s2 = s1.dropna().astype(int)
count_180 = (s2 == 180).sum()
print(count_180)

2

In [23]:
#5 处理身高数据为数值类型
s2.dtype

dtype('int32')

In [24]:
#6统计185以上身高的球员个数
s2[s2>185].count()
'=='*30

3

'============================================================'

In [26]:
#导入player_attributes表数据
df=pd.read_csv('player_attributes.csv')
df

,id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,0,505942,2016/2/18 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,1,505942,2015/11/19 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,2,505942,2015/9/21 0:00,62.0,66.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,3,505942,2015/3/20 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,4,505942,2007/2/22 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183973,183973,39902,2009/8/30 0:00,83.0,85.0,right,medium,low,84.0,77.0,...,88.0,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0
183974,183974,39902,2009/2/22 0:00,78.0,80.0,right,medium,low,74.0,76.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183975,183975,39902,2008/8/30 0:00,77.0,80.0,right,medium,low,74.0,71.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183976,183976,39902,2007/8/30 0:00,78.0,81.0,right,medium,low,74.0,64.0,...,88.0,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0
183977,183977,39902,2007/2/22 0:00,80.0,81.0,right,medium,low,74.0,68.0,...,88.0,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0

In [76]:
#显示player_attributes表的各项属性
df.dtypes

id                       int64
player_api_id            int64
date                    object
overall_rating         float64
potential              float64
preferred_foot          object
attacking_work_rate     object
defensive_work_rate     object
crossing               float64
finishing              float64
heading_accuracy       float64
short_passing          float64
volleys                float64
dribbling              float64
curve                  float64
free_kick_accuracy     float64
long_passing           float64
ball_control           float64
acceleration           float64
sprint_speed           float64
agility                float64
reactions              float64
balance                float64
shot_power             float64
jumping                float64
stamina                float64
strength               float64
long_shots             float64
aggression             float64
interceptions          float64
positioning            float64
vision                 float64
penalties              float64
marking                float64
standing_tackle        float64
sliding_tackle         float64
gk_diving              float64
gk_handling            float64
gk_kicking             float64
gk_positioning         float64
gk_reflexes            float64
dtype: object

In [27]:
#尝试修改某些列的数据类型
df['id'].dtypes
df=df.astype({'id':'float64'})
df['id'].dtypes

dtype('int64')

dtype('float64')

In [78]:
#尝试修改某些列的列名
df.columns
df=df.rename(columns={'id':'编号'})
df.columns

Index(['id', 'player_api_id', 'date', 'overall_rating', 'potential',
       'preferred_foot', 'attacking_work_rate', 'defensive_work_rate',
       'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys',
       'dribbling', 'curve', 'free_kick_accuracy', 'long_passing',
       'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions',
       'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots',
       'aggression', 'interceptions', 'positioning', 'vision', 'penalties',
       'marking', 'standing_tackle', 'sliding_tackle', 'gk_diving',
       'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes'],
      dtype='object')

Index(['编号', 'player_api_id', 'date', 'overall_rating', 'potential',
       'preferred_foot', 'attacking_work_rate', 'defensive_work_rate',
       'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys',
       'dribbling', 'curve', 'free_kick_accuracy', 'long_passing',
       'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions',
       'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots',
       'aggression', 'interceptions', 'positioning', 'vision', 'penalties',
       'marking', 'standing_tackle', 'sliding_tackle', 'gk_diving',
       'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes'],
      dtype='object')

In [28]:
#调用相关描述函数査看player_attributes表数据信息
df.shape
df.index
df.columns
df.info()
df

(183978, 41)

RangeIndex(start=0, stop=183978, step=1)

Index(['id', 'player_api_id', 'date', 'overall_rating', 'potential',
       'preferred_foot', 'attacking_work_rate', 'defensive_work_rate',
       'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys',
       'dribbling', 'curve', 'free_kick_accuracy', 'long_passing',
       'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions',
       'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots',
       'aggression', 'interceptions', 'positioning', 'vision', 'penalties',
       'marking', 'standing_tackle', 'sliding_tackle', 'gk_diving',
       'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes'],
      dtype='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183978 entries, 0 to 183977
Data columns (total 41 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   183978 non-null  float64
 1   player_api_id        183978 non-null  int64
 2   date                 183978 non-null  object
 3   overall_rating       183142 non-null  float64
 4   potential            183142 non-null  float64
 5   preferred_foot       183142 non-null  object
 6   attacking_work_rate  177109 non-null  object
 7   defensive_work_rate  183142 non-null  object
 8   crossing             183142 non-null  float64
 9   finishing            183142 non-null  float64
 10  heading_accuracy     183142 non-null  float64
 11  short_passing        183142 non-null  float64
 12  volleys              181265 non-null  float64
 13  dribbling            183142 non-null  float64
 14  curve                181265 non-null  float64
 15  free_kick_accuracy   183142 non-null  float64
 16  long_passing         183142 non-null  float64
 17  ball_control         183142 non-null  float64
 18  acceleration         183142 non-null  float64
 19  sprint_speed         183142 non-null  float64
 20  agility              181265 non-null  float64
 21  reactions            183142 non-null  float64
 22  balance              181265 non-null  float64
 23  shot_power           183142 non-null  float64
 24  jumping              181265 non-null  float64
 25  stamina              183142 non-null  float64
 26  strength             183142 non-null  float64
 27  long_shots           183142 non-null  float64
 28  aggression           183142 non-null  float64
 29  interceptions        183142 non-null  float64
 30  positioning          183142 non-null  float64
 31  vision               181265 non-null  float64
 32  penalties            183142 non-null  float64
 33  marking              183142 non-null  float64
 34  standing_tackle      183142 non-null  float64
 35  sliding_tackle       181265 non-null  float64
 36  gk_diving            183142 non-null  float64
 37  gk_handling          183142 non-null  float64
 38  gk_kicking           183142 non-null  float64
 39  gk_positioning       183142 non-null  float64
 40  gk_reflexes          183142 non-null  float64
dtypes: float64(36), int64(1), object(4)
memory usage: 57.5+ MB

,id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,0.0,505942,2016/2/18 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,1.0,505942,2015/11/19 0:00,67.0,71.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,2.0,505942,2015/9/21 0:00,62.0,66.0,right,medium,medium,49.0,44.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,3.0,505942,2015/3/20 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,4.0,505942,2007/2/22 0:00,61.0,65.0,right,medium,medium,48.0,43.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183973,183973.0,39902,2009/8/30 0:00,83.0,85.0,right,medium,low,84.0,77.0,...,88.0,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0
183974,183974.0,39902,2009/2/22 0:00,78.0,80.0,right,medium,low,74.0,76.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183975,183975.0,39902,2008/8/30 0:00,77.0,80.0,right,medium,low,74.0,71.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183976,183976.0,39902,2007/8/30 0:00,78.0,81.0,right,medium,low,74.0,64.0,...,88.0,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0
183977,183977.0,39902,2007/2/22 0:00,80.0,81.0,right,medium,low,74.0,68.0,...,88.0,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0

In [30]:
#统计某一列包含空值的数量
df1=df['gk_diving'].isnull().sum()
df1

'=='*30

836

'============================================================'

In [31]:
#显示数据的行列数量
ta=pd.read_csv('team_attributes.csv')
ta
ta.shape

,id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,buildUpPlayPositioningClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
0,0,9930,2010/2/22 0:00,60,Balanced,NaN,Little,50,Mixed,Organised,...,55,Normal,Organised,50,Medium,55,Press,45,Normal,Cover
1,1,9930,2014/9/19 0:00,52,Balanced,48.0,Normal,56,Mixed,Organised,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
2,2,9930,2015/9/10 0:00,47,Balanced,41.0,Normal,54,Mixed,Organised,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
3,3,8485,2010/2/22 0:00,70,Fast,NaN,Little,70,Long,Organised,...,70,Lots,Organised,60,Medium,70,Double,70,Wide,Cover
4,4,8485,2011/2/22 0:00,47,Balanced,NaN,Little,52,Mixed,Organised,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1453,1453,10000,2011/2/22 0:00,52,Balanced,NaN,Little,52,Mixed,Organised,...,53,Normal,Organised,46,Medium,48,Press,53,Normal,Cover
1454,1454,10000,2012/2/22 0:00,54,Balanced,NaN,Little,51,Mixed,Organised,...,50,Normal,Organised,44,Medium,55,Press,53,Normal,Cover
1455,1455,10000,2013/9/20 0:00,54,Balanced,NaN,Little,51,Mixed,Organised,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover
1456,1456,10000,2014/9/19 0:00,54,Balanced,42.0,Normal,51,Mixed,Organised,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover
1457,1457,10000,2015/9/10 0:00,54,Balanced,42.0,Normal,51,Mixed,Organised,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover

(1458, 24)

In [32]:
#显示team_api_id列
ta['team_api_id']

0        9930
1        9930
2        9930
3        8485
4        8485
        ...
1453    10000
1454    10000
1455    10000
1456    10000
1457    10000
Name: team_api_id, Length: 1458, dtype: int64

In [33]:
#显示team_api_id和其他列
ta.columns

Index(['id', 'team_api_id', 'date', 'buildUpPlaySpeed',
       'buildUpPlaySpeedClass', 'buildUpPlayDribbling',
       'buildUpPlayDribblingClass', 'buildUpPlayPassing',
       'buildUpPlayPassingClass', 'buildUpPlayPositioningClass',
       'chanceCreationPassing', 'chanceCreationPassingClass',
       'chanceCreationCrossing', 'chanceCreationCrossingClass',
       'chanceCreationShooting', 'chanceCreationShootingClass',
       'chanceCreationPositioningClass', 'defencePressure',
       'defencePressureClass', 'defenceAggression', 'defenceAggressionClass',
       'defenceTeamWidth', 'defenceTeamWidthClass',
       'defenceDefenderLineClass'],
      dtype='object')

In [34]:
#添加area列的值为Europe
ta['area']='Europe'
ta['area']

0       Europe
1       Europe
2       Europe
3       Europe
4       Europe
         ...
1453    Europe
1454    Europe
1455    Europe
1456    Europe
1457    Europe
Name: area, Length: 1458, dtype: object

In [39]:
#增加buildUpPlayAvg列并赋值为buildUpPlaySpeed\df.buildUpPlayDribbling\df.buildUpPlayPassing的均值
ta['buildUpPlayAvg'] = ta[['buildUpPlaySpeed', 'buildUpPlayDribbling', 'buildUpPlayPassing']].mean(axis=1)
ta.buildUpPlayAvg

0       55.000000
1       52.000000
2       47.333333
3       70.000000
4       49.500000
          ...
1453    52.000000
1454    52.500000
1455    52.500000
1456    49.000000
1457    49.000000
Name: buildUpPlayAvg, Length: 1458, dtype: float64